### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by faucetlol** [SixGrid/sixgrid#13]
Unable to start the app on 6.1.2-arch1-1 with the latest Nvidia 525 drivers.

```
[3242:0103/084128.559210:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

It does seem to run when using `./sixgrid --no-sandbox` but that doesn't seem like an ideal solution.

**Comment by ktwrd** [comment]
Seems like this is an electron related issue, and from looking at issues on other electron projects that have the same error using `--no-sandbox` does fix it for Electron 11.x

I also found that (maybe) adding `--in-process-gpu` *might* fix this, but I'll see if that does when I get home. ([src](https://stackoverflow.com/a/70840422))

**Comment by faucetlol** [comment]
Can confirm that `--in-process-gpu` also works

**Comment by ktwrd** [comment]
Is that just with `./sixgrid --in-process-gpu` or `./sixgrid --no-sandbox --in-process-gpu`?

**Comment by faucetlol** [comment]
Just with `./sixgrid --in-process-gpu`

**Comment by ktwrd** [comment]
@faucetlol2 Can you try running sixgrid with no arguments with this release?
https://github.com/SixGrid/sixgrid/releases/tag/v0.3.6-3-bug-gpuprocessisntusable

**Comment by faucetlol** [comment]
That works!
